REHAB X CENTRAL SOFTWARE DEVELOPMENT PLATFORM 
  1)EMBEDDED SOFTWARE  
    -HAPTIC MOTORS
    -MPU6050 SENSORS 
    -3D MODELING 
  2) REAL TIME HUMAN POSE ESTIMATION 
    - 
    - 
  
This line was added by Eric
